[package]
name = "nightfury-server"
version = "0.1.0"
edition = "2024"

[dependencies]
bufstream = "0.1.4"
ctrlc = "3.4.7"
nightfury = {path = "../nightfury", features = ["thread-safe"]}
serde = "1.0.219"
serde_json = "1.0.140"
