[package]
name = "nightfury-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
bufstream = "0.1.4"
clap = { version = "4.5.40", features = ["derive"] }
nightfury = {path = "../nightfury"}
serde_json = "1.0.140"
