name: Rust

on:
  push:
    branches: [ "releases" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: need the nightly rust toolchain version since we use some unstable features
      run: rustup override set nightly
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (release)
      run: cargo test -r --verbose
    - name: Login into crates.io
      run: cargo login ${{ secrets.CRATES_IO }}
    - name: Build binaries in "release" mode
      run: cargo build -r
    - name: "Package for crates.io"
      run: ./cargo_ignore_errors.sh package # publishes a package as a tarball
    - name: "Publish to crates.io"
      run: ./cargo_ignore_errors.sh publish # publishes your crate as a library that can be added as a dependency

